name: Integration Tests

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies (root)
        run: npm ci

      - name: Build data package first
        run: npm run build:data

      - name: Unit tests (workspaces)
        run: npm run test:unit

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: E2E tests
        env:
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
        run: npm run test:e2e
